extraObjects:
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: opentelemetry
    namespace: ingress-nginx
  spec:
    exporter:
      endpoint: http://localhost:4317
    propagators:
      - tracecontext
      - baggage
      - b3
    sampler:
      type: parentbased_traceidratio
      argument: "0.25"
    python:
      env:
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://localhost:4317
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://localhost:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
    java:
      env:
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://localhost:4317
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://localhost:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
    nginx:
      env:
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://localhost:4317
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://localhost:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
