alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.tronic.sk
    ingressClassName: nginx
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.tronic.sk
    ingressClassName: nginx
  admin:
    existingSecret: "grafana-admin-secret"
prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.tronic.sk
    ingressClassName: nginx
