globals:
  repoURL: git@github.com:lukas-pastva/kubernetes.git
  

appProjects:
  - namespace: kube-system
    applications:
      - name: rke2-cilium
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
  - namespace: opentelemetry
    applications:
      - name: opentelemetry-operator
        path: external/opentelemetry-helm/opentelemetry-operator/0.91.1
        autoSync: true
      - name: opentelemetry-collector
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
  - namespace: rancher
    applications:
      - name: rancher
        path: external/rancher-stable/rancher/2.11.3
        autoSync: true
  - namespace: openebs
    applications:
      - name: openebs
        path: external/openebs/openebs/4.3.2
        autoSync: true
  - namespace: metallb-system
    applications:
      - name: metallb
        path: external/metallb/metallb/0.15.2
        autoSync: true
      - name: metallb-iap
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
  - namespace: monitoring
    applications:
      - name: kube-prometheus-stack-crds
        path: >-
          external/prometheus-community/kube-prometheus-stack/75.9.0/charts/crds/crds
        autoSync: true
        replace: true
      - name: kube-prometheus-stack
        path: external/prometheus-community/kube-prometheus-stack/75.9.0
        autoSync: true
        skipCrds: true
      - name: promtail
        path: external/grafana/promtail/6.17.0
        autoSync: true
      - name: loki
        path: external/grafana/loki/6.30.1
        autoSync: true
      - name: thanos
        path: external/bitnami/thanos/17.2.1
        autoSync: true
      - name: tempo
        path: external/grafana/tempo-distributed/1.45.0
        autoSync: true
  - namespace: ingress-nginx
    applications:
      - name: ingress-nginx-extra
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
      - name: ingress-nginx
        path: external/ingress-nginx/ingress-nginx/4.13.0
        autoSync: true
  - namespace: oauth2-google
    applications:
      - name: oauth2-google
        path: external/oauth2-proxy/oauth2-proxy/7.9.0
        autoSync: true
  - namespace: argocd
    applications:
      - name: argocd
        path: external/argo/argo-cd/8.1.2
        autoSync: true
  - namespace: argo-workflows
    applications:
      - name: argo-events
        path: external/argo/argo-events/2.4.15
        autoSync: true
      - name: argo-workflows
        path: external/argo/argo-workflows/0.45.19
        autoSync: true
      - name: argo-workflows-ui
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
      - name: event-backup-gl
        path: internal/events
        autoSync: true
      - name: event-backup-gh
        path: internal/events
        autoSync: true
      - name: event-backup-k8s
        path: internal/events
        autoSync: true
      - name: event-stop
        path: internal/events
        autoSync: true
      - name: event-deploy
        path: internal/events
        autoSync: true
      - name: event-install
        path: internal/events
        autoSync: true
      - name: event-upgrade
        path: internal/events
        autoSync: true
      - name: event-download
        path: internal/events
        autoSync: true
      - name: event-delete
        path: internal/events
        autoSync: true
      - name: argo-app-manager
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
  - namespace: cert-manager
    applications:
      - name: cert-manager
        path: external/cert-manager/cert-manager/1.18.2
        autoSync: true
  - namespace: csi-s3
    applications:
      - name: csi-s3
        path: external/k8s-csi-s3/csi-s3/0.43.0
        autoSync: true
  - namespace: ingress-browser
    applications:
      - name: ingress-browser
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
  - namespace: web-example
    applications:
      - name: web-example
        path: external/lukas-pastva/helm-chartie/1.0.8
        autoSync: true
