{{- range $onePasswordSecret := .Values.onePasswordSecrets }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $onePasswordSecret.name }}
  namespace: {{ $onePasswordSecret.namespace }}
spec:
  itemPath: "vaults/{{ $.Values.vaultName | default "kubernetes" }}/items/{{ $onePasswordSecret.name }}"
type: {{ $onePasswordSecret.type | default "Opaque" | quote }}
{{- end }}